- type: job
  id: DirectorOfCare
  name: job-name-doc
  description: job-description-doc
  playTimeTracker: JobDirectorOfCare
  salary: 80000 # Horizon
  forceFaction: FactionMed # Horizon
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hrs
  #  whitelisted: true # Horizon TempTweak
  startingGear: DocGear
  alwaysUseSpawner: true
  icon: "JobIconDoc"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 170
  displayWeight: 55 # Second from the top
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: MedicalBountyBankPayment # any medical bounties sold go directly into the bank
        account: Medical
      - type: PreventShipyardTitleOverwrite
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: DocGear
  equipment:
    pocket1: Hypospray # Horizon
    pocket2: MedicalAppraisalTool
  storage:
    back:
    - StationAdministrationConsoleFlatpack
    - MobileComputerTabletopCommsFlatpack
    - BoxFolderMedicalDoctor
    - RubberStampDoc

- type: chameleonOutfit
  id: DirectorOfCareChameleonOutfit
  job: DirectorOfCare
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretCmo
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingCloakCmo
    outerClothing: ClothingOuterCoatLabCmo
    gloves: ClothingHandsGlovesNitrile
