################################################################################
##### General ##################################################################

[net]
port = 1212
bindto = "0.0.0.0"
log_late_msg = false

[database]
engine = "postgres"
pg_host = "database"
pg_port = 5432
pg_database = "ss14"
pg_username = "ss14_user"
pg_password = "%pg_password%"

[game]
hostname = "StarHorizon - Frontier [üí´] [18+]"
desc = """
–î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å –Ω–∞ –Ω–∞—à —Å–µ—Ä–≤–µ—Ä! –ú—ã –ø—Ä–µ–¥–ª–∞–≥–∞–µ–º –ø–æ–ª–Ω—É—é —Å–≤–æ–±–æ–¥—É –≤—ã–±–æ—Ä–∞!

–£ –Ω–∞—Å –≤—ã –≤—Å—Ç—Ä–µ—Ç–∏—Ç–µ:
ü©∫ –•–∏—Ä—É—Ä–≥–∏—é, –∏–º–ø–ª–∞–Ω—Ç—ã –∏ –∫–∏–±–µ—Ä–Ω–µ—Ç–∏–∫—É. –ù–∞–Ω–æ–º–∞—à–∏–Ω—ã, —Å—ã–Ω–æ–∫!
ü§ñ –ì–∏–≥–∞–Ω—Ç—Å–∫–∏—Ö –º–µ—Ö–æ–≤. –ü–æ–∫–∞–∂–∏ —ç—Ç–æ–º—É –î–∏–Ω–æ–∑–∞–≤—Ä—É, –∫—Ç–æ —Ç—É—Ç –ë–æ—Å—Å!
üå± –ü—Ä–æ–¥–≤–∏–Ω—É—Ç—É—é –±–æ—Ç–∞–Ω–∏–∫—É! –ú–Ω–æ–∂–µ—Å—Ç–≤–æ —Ä–∞—Å—Ç–µ–Ω–∏–π –∏ –≥–µ–Ω–µ—Ç–∏–∫–∞.
üß® –£–ª—É—á—à–∞–µ–º–æ–µ –≤–æ–æ—Ä—É–∂–µ–Ω–∏–µ –∏ –º–æ–¥—É–ª–∏.
üî¨ –£–Ω–∏–∫–∞–ª—å–Ω—ã–µ —Ç–µ—Ö–Ω–æ–ª–æ–≥–∏–∏.
üèØ –°–æ–∑–¥–∞–Ω–∏–µ —Å–≤–æ–µ–≥–æ –∫–ª–∞–Ω–∞ –∏ —Ñ—Ä–∞–∫—Ü–∏–∏!
üé∂ –ü–æ–ª–Ω–æ—Ü–µ–Ω–Ω—ã–π –∞–Ω–∞–ª–æ–≥ –¢–¢–° - –ë–∞—Ä–∫–∏!

–ó–∞—Ö–æ–¥–∏, –±—É–¥–µ—Ç –≤–µ—Å–µ–ª–æ!
"""
soft_max_players = 100
lobbyduration = 180
defaultpreset = "nfpirate"
fallbackpreset = "nfadventure"

[hub]
advertise = true
tags = "lang:ru,region:eu_e,rp:med"
server_url = "ss14://ss14.starhorizon.ru:1212"
# Wizard's Den hub
hub_urls = "https://hub.spacestation14.com/"

[server]
rules_file = "FrontierRuleset"
lobby_name = "StarHorizon"

[console]
# –£–∫–∞–∑–∞—Ç—å CKey –∏–≥—Ä–æ–∫–∞, –∫–æ—Ç–æ—Ä—ã–π –ø–æ-—É–º–æ–ª—á–∞–Ω–∏—é –∏ –Ω–µ –∑–∞–≤–∏—Å–∏–º–æ –Ω–∏ –æ—Ç —á–µ–≥–æ
# –±—É–¥–µ—Ç –∏–º–µ—Ç—å –ù–ê–ò–í–´–°–®–ò–ï –ø—Ä–∞–≤–∞ –Ω–∞ —Å–µ—Ä–≤–µ—Ä–µ (HOST)
login_host_user = "EvilBug"

[admin]
see_own_notes = true
note_fresh_days = 0
message_wait_time = 1
new_player_threshold = 180
afk_time = 180.0
admins_count_in_playercount = true # –æ—Ç–æ–±—Ä–∞–∂–∞–µ—Ç –∞–¥–º–∏–Ω–æ–≤ –≤ —Å—á–µ—Ç—á–∏–∫–µ
chat_discord_channel_id = 1408835997449588746

[interaction]
rate_limit_announce_admins_delay = -1 # —É–±–∏—Ä–∞–µ—Ç —Å–ø–∞–º –æ –ø—Ä–µ–≤—ã—à–µ–Ω–∏–∏ –ª–∏–º–∏—Ç–æ–≤ –∏–≥—Ä–æ–∫–æ–º

[ahelp]
admin_prefix = true # –æ—Ç–æ–±—Ä–∞–∂–∞–µ—Ç —Ä–∞–Ω–≥ –∞–¥–º–µ–º–∞ –≤ –ê–•–µ–ª–ø
admin_prefix_webhook = true

[infolinks]
discord = "https://discord.starhorizon.ru"
#wiki = "https://wiki.starhorizon.ru/"

################################################################################
##### In Game ##################################################################

[atmos]
space_wind = true
monstermos_rip_tiles = true
mmos_spacing_speed = 0.95
mmos_max_wind = 1000.0

[biomass]
easy_mode = false

[vote]
timermap = 30
map_enabled = true
restart_not_allowed_when_admin_online = false

[shuttle]
auto_call_time = 1440
emergency_authorize_time = 30
impact.enabled = true
impact.tile_break_energy = 3000.0
impact.damage_multiplier = 0.00010
impact.spark_energy = 2000000.0
impact.slowdown = 8.0
impact.min_throw_velocity = 1.0
impact.inertia_scaling = 0.5

[rules]
time = 90.0

[tips]
enabled = false

[chat]
max_announcement_length = 2048

[ic]
flavor_text = true
flavor_text_length = 1024

[ooc]
enabled_admin = false

################################################################################
##### Metrics ##################################################################

[metrics]
enabled = true
host = "ss14"
port = 9001
#runtime = false

[loki]
enabled = false
#address = "http://127.0.0.1:3100"
#name = "aavikko_ss14_main"

################################################################################
##### Discord ##################################################################

[discord]
ahelp_webhook = "%webhook_ahelp%"
ban_webhook = "%webhook_ban%"
round_update_webhook = "%webhook_round_update%"
leaderboard_webhook = "%webhook_round_update%"
guild_id = 1348258341658562560
token = "%bot_token%"

################################################################################
##### Relpay ###################################################################

[replay]
auto_record = true
directory = "replays/"
